### ISSUE TITLE
App Crash, When clicking on "love / likes history" icon more than one click.

### ISSUE THREAD

**Issue by rezamusic881** [DDihanov/musiQ#25]
#### <center>Expected behavior</center>

<center>Supposedly, the app does not stop when logged in on the "History feature" and click the love / likes history icon more than "one click", after playing the video from the streaming site.</center>

#### <center>Actual behavior</center>

<center>At first I felt strange, suddenly the application crashes when I click the "love / likes history" icon in the "history feature" when I just finished watching the video on the streaming site, Then I chased the error and I found it. the app stops when you enter the "History feature" and click the likes / likes of history more than "one click", after playing the video from the streaming site.</center>

#### How to reproduce
- Instal [musiQ app](https://play.google.com/store/apps/details?id=com.dihanov.musiq) and Sign Up account, then login. after successfully logging in, close and exit the app.
- Go to the streaming site and watch a few minutes of video in it.
- After playing the video, just open the musiQ app and on "History feature" you can find the history of the video you just watched. then click on "love / likes history icon" more than one click. then the application will crash.

##### <center>App Version : 1.860</center>

***

#### <center>Record of the issues</center>

https://youtu.be/gBLsRN2P9io

#### Logcat
```06-20 23:37:09.484 31503 31503 E AndroidRuntime: FATAL EXCEPTION: main
06-20 23:37:09.484 31503 31503 E AndroidRuntime: Process: com.dihanov.musiq, PID: 31503
06-20 23:37:09.484 31503 31503 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.dihanov.musiq.models.Artist.getName()' on a null object reference
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at com.dihanov.musiq.ui.detail.ArtistDetails$1.onPostExecute(ArtistDetails.java:161)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at com.dihanov.musiq.ui.detail.ArtistDetails$1.onPostExecute(ArtistDetails.java:148)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:667)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6361)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
06-20 23:37:09.484 31503 31503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)```

**Comment by DDihanov** [comment]
Hello! Thank you for the report. In the video you just click on the heart button multiple times, but in the description you mention clicking on the "history" feature and hitting "like" from there. What is this "like" feature you are talking about?
